Appium instrumentation test cases

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,43 +47,105 @@ jobs:
 #            path: app/build/reports/tests/testDebugUnitTest/
 
 
+#  instrumentation-test:
+##    needs: [ unit-test ]
+#    runs-on: macos-latest
+#    continue-on-error: true
+#    steps:
+#      - name: Checkout the code
+#        uses: actions/checkout@v3
+#
+#      - name: Set up JDK 17
+#        uses: actions/setup-java@v4
+#        with:
+#          java-version: 17
+#          distribution: 'adopt'
+#
+#
+#      - name: Make gradlew executable
+#        run: chmod +x ./gradlew
+#
+#      - name: Setup Android SDK
+#        uses: android-actions/setup-android@v3
+#
+#      - name: Run espresso tests
+#        uses: reactivecircus/android-emulator-runner@v2
+#        with:
+#          api-level: 26
+#          target: default
+#          arch: x86_64
+#          profile: Nexus 4
+#          avd-name: test
+#          emulator-options: "-no-window -no-audio -no-boot-anim -no-snapshot-load"
+#          script: |
+#            adb wait-for-device
+#            adb shell input keyevent 82
+#            ./gradlew connectedAndroidTest --continue
+#
+#      - name: Upload test report
+#        if: failure()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: instrumentation_test_report
+#          path: app/build/reports/androidTests/connected/
+
+
+
   instrumentation-test:
-#    needs: [ unit-test ]
-    runs-on: macos-latest
-    continue-on-error: true
+    runs-on: ubuntu-latest
+    outputs:
+      maven_tests: ${{ steps.maven_tests.outcome }}
+
     steps:
-      - name: Checkout the code
-        uses: actions/checkout@v3
+      - name: Enable KVM
+        run: |
+          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
+          sudo udevadm control --reload-rules
+          sudo udevadm trigger --name-match=kvm
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
+      - name: Checkout project
+        uses: actions/checkout@v4
+
+      - name: Set up JDK
+        uses: actions/setup-java@v3
         with:
-          java-version: 17
-          distribution: 'adopt'
+          distribution: 'temurin'
+          java-version: '17'
+          cache: maven
 
+      - name: Build with Maven
+        run: mvn install -DskipTests
 
-      - name: Make gradlew executable
-        run: chmod +x ./gradlew
+      - name: Start Appium Server
+        run: |
+          chmod +x ./scripts/prepareAppiumServer.sh
+          ./scripts/prepareAppiumServer.sh
 
-      - name: Setup Android SDK
-        uses: android-actions/setup-android@v3
-
-      - name: Run espresso tests
+      - name: Run tests on Android emulators
+        id: maven_tests
         uses: reactivecircus/android-emulator-runner@v2
         with:
-          api-level: 26
-          target: default
+          api-level: 28
+          target: google_apis
           arch: x86_64
-          profile: Nexus 4
-          avd-name: test
-          emulator-options: "-no-window -no-audio -no-boot-anim -no-snapshot-load"
+          profile: Nexus 6
           script: |
-            adb wait-for-device
-            adb shell input keyevent 82
-            ./gradlew connectedAndroidTest --continue
+            chmod +x ./scripts/start_emulator_2.sh
+            ./scripts/start_emulator_2.sh
+          
+            chmod +x ./scripts/uploadAPK.sh
+            ./scripts/uploadAPK.sh
+          
+            mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testng-local.xml || true
+          
+            echo "Closing connection with emulator-5554"
+            adb -s emulator-5554 emu kill || true
+          
+            echo "Closing connection with emulator-5556"
+            adb -s emulator-5556 emu kill || true
 
-      - name: Upload test report
-        if: failure()
+      - name: Upload results (emulador)
+        if: always()
         uses: actions/upload-artifact@v4
         with:
           name: instrumentation_test_report
